# Generated by Django 4.2.11 on 2026-09-14 19:19
"""Derive spending windows, add money invariants, add replay protection.

The three AddConstraint operations below are the first database-level
guarantees this schema has ever had. Everything they assert was previously
"enforced" only by MinValueValidator, which Django runs during full_clean() and
therefore never on the .save() paths this codebase actually uses.

That makes applying them a data question, not just a schema one: if any row
already violates a constraint, PostgreSQL rejects the ALTER TABLE and the
migration fails partway through a deploy. The preflight check below runs first
and fails with an explicit report of what is wrong and where, instead of an
opaque "check constraint is violated by some row".

It deliberately does NOT repair anything. These are financial rows; a migration
that quietly rewrites balances is far worse than one that stops and asks.
"""

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


def check_existing_rows_satisfy_invariants(apps, schema_editor):
    """Fail loudly, with detail, if live data violates the new constraints."""
    Wallet = apps.get_model('wallets', 'Wallet')
    Transaction = apps.get_model('wallets', 'Transaction')
    SpendingLimit = apps.get_model('wallets', 'SpendingLimit')

    problems = []

    negative_wallets = Wallet.objects.filter(balance__lt=0)
    if negative_wallets.exists():
        ids = list(negative_wallets.values_list('id', flat=True)[:20])
        problems.append(
            f"{negative_wallets.count()} wallet(s) have a negative balance. "
            f"First ids: {ids}"
        )

    bad_amounts = Transaction.objects.filter(amount__lte=0)
    if bad_amounts.exists():
        ids = list(bad_amounts.values_list('id', flat=True)[:20])
        problems.append(
            f"{bad_amounts.count()} transaction(s) have amount <= 0. "
            f"First ids: {ids}"
        )

    bad_limits = SpendingLimit.objects.filter(
        models.Q(daily_limit__lt=0)
        | models.Q(weekly_limit__lt=0)
        | models.Q(monthly_limit__lt=0)
    )
    if bad_limits.exists():
        ids = list(bad_limits.values_list('id', flat=True)[:20])
        problems.append(
            f"{bad_limits.count()} spending limit(s) have a negative limit. "
            f"First ids: {ids}"
        )

    if problems:
        raise RuntimeError(
            "Refusing to add money invariants: existing rows violate them.\n\n"
            + "\n".join(f"  * {p}" for p in problems)
            + "\n\nInvestigate and correct these rows, then re-run the migration. "
              "Do not 'fix' them by relaxing the constraint -- each one is "
              "evidence of a real write that should not have been possible."
        )


def noop_reverse(apps, schema_editor):
    """Nothing to undo: the check above never writes."""


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            check_existing_rows_satisfy_invariants,
            noop_reverse,
        ),
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=255)),
                ('endpoint', models.CharField(max_length=200)),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('response_status', models.PositiveSmallIntegerField()),
                ('response_body', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'idempotency_records',
            },
        ),
        migrations.RemoveField(
            model_name='spendinglimit',
            name='daily_spent',
        ),
        migrations.RemoveField(
            model_name='spendinglimit',
            name='monthly_spent',
        ),
        migrations.RemoveField(
            model_name='spendinglimit',
            name='weekly_spent',
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'category', 'created_at'], name='txn_user_category_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='spendinglimit',
            constraint=models.CheckConstraint(check=models.Q(('daily_limit__gte', 0), ('weekly_limit__gte', 0), ('monthly_limit__gte', 0)), name='spending_limit_amounts_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='transaction_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(check=models.Q(('balance__gte', 0)), name='wallet_balance_non_negative'),
        ),
        migrations.AddField(
            model_name='idempotencyrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='idempotencyrecord',
            index=models.Index(fields=['created_at'], name='idempotency_created_3fb3ea_idx'),
        ),
        migrations.AddConstraint(
            model_name='idempotencyrecord',
            constraint=models.UniqueConstraint(fields=('user', 'key'), name='idempotency_user_key_unique'),
        ),
    ]
