# Generated by Django 4.2.11 on 2026-07-18 04:59

from django.db import migrations


def backfill_wallets(apps, schema_editor):
    """
    Create a Wallet for any parent/student user that doesn't already have
    one. Needed because no code path ever created a Wallet before the
    post_save signal (added alongside this migration) started doing so —
    every user registered up to this point has none.
    """
    User = apps.get_model('accounts', 'User')
    Wallet = apps.get_model('wallets', 'Wallet')

    users_missing_wallets = User.objects.filter(
        role__in=('parent', 'student'),
        wallet__isnull=True,
    )
    Wallet.objects.bulk_create([
        Wallet(user=user) for user in users_missing_wallets
    ])


def noop_reverse(apps, schema_editor):
    # Intentionally not deleting wallets on reverse — that would destroy
    # real balances/history. Reversing this migration is a no-op.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_add_frozen_status_and_fraud_fields_to_transaction'),
    ]

    operations = [
        migrations.RunPython(backfill_wallets, noop_reverse),
    ]
