# apps/payments/models.py
from django.db import models
from django.conf import settings
from django.core.validators import MinValueValidator, MaxValueValidator
import uuid

# ---------------------------------------------------------------------------
# Fraud-related choice constants
# These are defined at module level so they can be imported by other modules
# (e.g. fraud detection rules, serializers, and admin classes) without
# duplicating the strings and risking typos.
# ---------------------------------------------------------------------------

FRAUD_SEVERITY_CHOICES = [
    ('low', 'Low'),
    ('medium', 'Medium'),
    ('high', 'High'),
    ('critical', 'Critical'),
]

FRAUD_STATUS_CHOICES = [
    ('pending', 'Pending'),
    ('investigating', 'Investigating'),
    ('confirmed', 'Confirmed'),
    ('false_positive', 'False Positive'),
    ('resolved', 'Resolved'),
]

FRAUD_ALERT_TYPE_CHOICES = [
    ('large_single_transaction', 'Large Single Transaction'),
    ('velocity_hourly', 'Hourly Velocity'),
    ('velocity_daily', 'Daily Velocity'),
    ('hourly_volume_exceeded', 'Hourly Volume Exceeded'),
    ('unusual_hours', 'Unusual Hours'),
    ('new_recipient_large', 'Large To New Recipient'),
    ('multiple_rules', 'Multiple Rules Triggered'),
    ('rapid_succession', 'Rapid Succession'),
]


class Merchant(models.Model):
    """
    Represents a verified business that can accept HapoPay payments.

    Merchants are created by admins and must be marked `verified=True`
    before they can generate QR codes or receive payments. Each merchant
    has a category (retail, restaurant, etc.) which is used by the
    spending-limit system to enforce per-category caps for students.
    """

    CATEGORY_CHOICES = [
        ('retail', 'Retail'),
        ('restaurant', 'Restaurant'),
        ('transport', 'Transport'),
        ('entertainment', 'Entertainment'),
        ('education', 'Education'),
        ('healthcare', 'Healthcare'),
        ('airtime', 'Airtime'),
        ('other', 'Other'),
    ]

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=200)
    business_registration = models.CharField(max_length=100, unique=True)
    email = models.EmailField()
    phone = models.CharField(max_length=15)
    address = models.TextField()
    category = models.CharField(max_length=20, choices=CATEGORY_CHOICES)
    verified = models.BooleanField(default=False)
    verified_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='verified_merchants'
    )
    verified_at = models.DateTimeField(null=True, blank=True)
    logo_url = models.URLField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'merchants'
        ordering = ['-created_at']

    def __str__(self):
        """Human-readable representation shown in the Django admin."""
        try:
            return f"{self.name} - {self.category}"
        except Exception:
            # Defensive: never let __str__ raise inside admin/logging
            return f"Merchant<{self.pk}>"


class QRCode(models.Model):
    """
    A short-lived payment token generated by a merchant.

    The customer (student) scans the QR image, which encodes the QRCode
    UUID. The backend validates that the QR has not expired and has not
    already been used before processing the payment. This prevents replay
    attacks where the same QR is scanned twice.
    """

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    merchant = models.ForeignKey(Merchant, on_delete=models.CASCADE, related_name='qr_codes')
    amount = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        validators=[MinValueValidator(0.01)]
    )
    description = models.CharField(max_length=200, blank=True, null=True)
    expires_at = models.DateTimeField()
    is_used = models.BooleanField(default=False)
    used_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True
    )
    used_at = models.DateTimeField(null=True, blank=True)
    qr_image = models.TextField(blank=True, null=True)  # Base64-encoded PNG
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'qr_codes'
        indexes = [
            models.Index(fields=['merchant', 'expires_at']),
            models.Index(fields=['is_used']),
        ]

    def __str__(self):
        try:
            return f"QR for {self.merchant.name} - {self.amount}"
        except Exception:
            return f"QRCode<{self.pk}>"


class NFCToken(models.Model):
    """
    A long-lived token bound to a specific user + device.

    Enables tap-to-pay: the student taps their phone on a merchant
    terminal, the terminal sends the token + amount to our API, and we
    debit the wallet. Tokens are unique per (user, device_id) pair so a
    single user can have multiple devices enrolled.
    """

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='nfc_tokens'
    )
    device_id = models.CharField(max_length=200)
    token = models.CharField(max_length=255, unique=True)
    is_active = models.BooleanField(default=True)
    expires_at = models.DateTimeField()
    last_used_at = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'nfc_tokens'
        unique_together = ['user', 'device_id']

    def __str__(self):
        try:
            return f"NFC Token for {self.user.email} - {self.device_id}"
        except Exception:
            return f"NFCToken<{self.pk}>"


class AirtimePurchase(models.Model):
    """
    Records a top-up of mobile airtime.

    Kept separate from `Transaction` so we can track provider-side
    metadata (transaction_id, provider status) without polluting the
    core ledger. On success we also create a `Transaction` row that
    actually debits the wallet.
    """

    PROVIDER_CHOICES = [
        ('vodacom', 'Vodacom'),
        ('mtn', 'MTN'),
        ('cellc', 'Cell C'),
        ('telkom', 'Telkom'),
        ('rain', 'Rain'),
    ]

    STATUS_CHOICES = [
        ('pending', 'Pending'),
        ('completed', 'Completed'),
        ('failed', 'Failed'),
        ('refunded', 'Refunded'),
    ]

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='airtime_purchases'
    )
    phone_number = models.CharField(max_length=15)
    amount = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        validators=[MinValueValidator(1)]
    )
    provider = models.CharField(max_length=20, choices=PROVIDER_CHOICES)
    status = models.CharField(max_length=30, choices=STATUS_CHOICES, default='pending')
    transaction_id = models.CharField(max_length=100, unique=True, null=True, blank=True)
    metadata = models.JSONField(default=dict, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    completed_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = 'airtime_purchases'
        ordering = ['-created_at']

    def __str__(self):
        try:
            return f"Airtime {self.amount} for {self.phone_number} ({self.provider})"
        except Exception:
            return f"AirtimePurchase<{self.pk}>"


class TransportTicket(models.Model):
    """
    A bus / train / taxi / ride-hailing ticket purchased through HapoPay.

    Stores the QR payload returned by the transport provider so the
    student can present it at boarding. The reference is the provider's
    booking ID, which we use to reconcile with their system.
    """

    TICKET_TYPES = [
        ('bus', 'Bus'),
        ('train', 'Train'),
        ('taxi', 'Taxi'),
        ('uber', 'Uber'),
        ('bolt', 'Bolt'),
    ]

    STATUS_CHOICES = [
        ('pending', 'Pending'),
        ('confirmed', 'Confirmed'),
        ('used', 'Used'),
        ('cancelled', 'Cancelled'),
        ('expired', 'Expired'),
    ]

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='transport_tickets'
    )
    ticket_type = models.CharField(max_length=20, choices=TICKET_TYPES)
    route = models.CharField(max_length=200)
    departure_time = models.DateTimeField()
    arrival_time = models.DateTimeField()
    amount = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        validators=[MinValueValidator(0.01)]
    )
    seat_number = models.CharField(max_length=20, blank=True, null=True)
    qr_code = models.TextField(blank=True, null=True)  # Base64 encoded ticket QR
    status = models.CharField(max_length=30, choices=STATUS_CHOICES, default='pending')
    reference = models.CharField(max_length=100, unique=True, null=True, blank=True)
    metadata = models.JSONField(default=dict, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'transport_tickets'
        ordering = ['-departure_time']

    def __str__(self):
        try:
            return f"{self.ticket_type} - {self.route} ({self.amount})"
        except Exception:
            return f"TransportTicket<{self.pk}>"


class FraudAlert(models.Model):
    """
    A single suspicious-activity record produced by the fraud engine.

    One FraudAlert is created per flagged transaction. `reasons` stores
    the list of rule names that fired (e.g. `["velocity_hourly",
    "unusual_hours"]`) so reviewers can see *why* the transaction was
    flagged. `alert_type` is the highest-priority rule and is used for
    quick filtering in the admin UI.
    """

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    transaction = models.ForeignKey(
        'wallets.Transaction',
        on_delete=models.CASCADE,
        related_name='fraud_alerts'
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='fraud_alerts'
    )
    alert_type = models.CharField(
        max_length=50,
        choices=FRAUD_ALERT_TYPE_CHOICES,
        default='multiple_rules'
    )
    reasons = models.JSONField(default=list)
    severity = models.CharField(
        max_length=30,
        choices=FRAUD_SEVERITY_CHOICES,
        default='low'
    )
    status = models.CharField(
        max_length=30,
        choices=FRAUD_STATUS_CHOICES,
        default='pending'
    )
    reviewed_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='reviewed_fraud_alerts'
    )
    reviewed_at = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    review_notes = models.TextField(blank=True, default='')
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'fraud_alerts'
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['severity']),
            models.Index(fields=['status']),
            models.Index(fields=['user']),
            models.Index(fields=['created_at']),
        ]

    def __str__(self):
        try:
            return f"FraudAlert [{self.severity}] - {self.user.email} - {self.status}"
        except Exception:
            return f"FraudAlert<{self.pk}>"