# Generated by Django 4.2.11 on 2026-07-18 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('parent', 'Parent'), ('student', 'Student'), ('admin', 'Admin'), ('merchant', 'Merchant')], default='parent', max_length=10),
        ),
    ]
