# Generated by Django 4.2.11 on 2026-09-14 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='last_streak_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='reward',
            index=models.Index(fields=['-points'], name='reward_points_desc_idx'),
        ),
    ]
