# Generated by Django 4.2.11 on 2026-07-18 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallets', '0002_backfill_missing_wallets'),
        ('payments', '0001_fix_fraud_alert_fk_and_add_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='owner',
            field=models.OneToOneField(blank=True, limit_choices_to={'role': 'merchant'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merchant_business', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('transaction_count', models.PositiveIntegerField(default=0)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_settlements', to=settings.AUTH_USER_MODEL)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='payments.merchant')),
                ('transactions', models.ManyToManyField(blank=True, related_name='settlements', to='wallets.transaction')),
            ],
            options={
                'db_table': 'settlements',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['merchant', 'status'], name='settlements_merchan_1f45d0_idx'), models.Index(fields=['period_start', 'period_end'], name='settlements_period__c1ab0c_idx')],
            },
        ),
    ]
